"use client";

import React, { useState, useEffect } from "react";
import {
  Settings,
  Download,
  Trash2,
  CheckCircle2,
  Clock,
  Bot,
  FileText,
} from "lucide-react";
import { FIXED_PLAN_START_DATE, FIXED_PLAN_END_DATE } from "@/lib/data";

export default function SettingsPage() {
  const [groqKey, setGroqKey] = useState("");
  const [selectedModel, setSelectedModel] = useState("openai/gpt-oss-120b");
  const [dailyHours, setDailyHours] = useState("6");
  const [savedSuccess, setSavedSuccess] = useState(false);

  useEffect(() => {
    const key = localStorage.getItem("gate_groq_api_key");
    if (key) setGroqKey(key);

    const model = localStorage.getItem("gate_ai_model");
    if (model) setSelectedModel(model);

    const hours = localStorage.getItem("gate_daily_hours");
    if (hours) setDailyHours(hours);
  }, []);

  const handleSaveSettings = () => {
    localStorage.setItem("gate_groq_api_key", groqKey);
    localStorage.setItem("gate_ai_model", selectedModel);
    localStorage.setItem("gate_daily_hours", dailyHours);
    setSavedSuccess(true);
    setTimeout(() => setSavedSuccess(false), 3000);
  };

  const handleExportErrorBookCsv = () => {
    try {
      const saved = localStorage.getItem("gate_error_book") || "[]";
      const list = JSON.parse(saved);

      if (list.length === 0) {
        alert("No mistakes currently logged in Error Book to export.");
        return;
      }

      const headers = ["Subject", "Topic", "Mistake Type", "My Answer", "Correct Answer", "Why Wrong", "Concept Missed", "Shortcut"];
      const rows = list.map((e: any) => [
        `"${e.subjectName}"`,
        `"${e.topic}"`,
        `"${e.mistakeType}"`,
        `"${e.userAnswer}"`,
        `"${e.correctAnswer}"`,
        `"${e.whyWrong}"`,
        `"${e.correctConcept}"`,
        `"${e.shortRule}"`,
      ]);

      const csvContent = [headers.join(","), ...rows.map((r: any) => r.join(","))].join("\n");
      const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.setAttribute("download", `GATE_Error_Book_${new Date().toISOString().slice(0, 10)}.csv`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (e) {
      console.warn("Export failed", e);
    }
  };

  const handleExportPreparationReport = () => {
    const report = `# GATE 2027 CS/IT — 90-Day Preparation Report
Generated: ${new Date().toLocaleString()}
Plan Start Date: ${FIXED_PLAN_START_DATE}
Plan End Date: ${FIXED_PLAN_END_DATE}
Target Daily Study: ${dailyHours} Hours/Day

## Preparation Rules Followed:
1. Subject dependency order strictly observed.
2. Weekly Sunday mock test and deep error analysis.
3. Every repeated mistake diagnosed in 13-Subject Error Book.

*Generated by GATE 2027 AI Preparation Platform*
`;
    const blob = new Blob([report], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `GATE_Preparation_Report_${new Date().toISOString().slice(0, 10)}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleClearProgress = () => {
    if (confirm("Are you sure you want to reset your local study checklist and history? This cannot be undone.")) {
      localStorage.removeItem("gate_study_days");
      localStorage.removeItem("gate_error_book");
      localStorage.removeItem("gate_revision_cards");
      localStorage.removeItem("gate_day_notes");
      alert("Local study data reset successfully.");
      window.location.reload();
    }
  };

  return (
    <div className="space-y-8 max-w-4xl mx-auto pb-20 animate-fade-in-up">
      {/* Header Banner - Liquid Glass */}
      <div className="luxury-glass border border-white/90 rounded-3xl p-6 sm:p-8 shadow-lg">
        <div className="max-w-2xl space-y-2">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-black luxury-glass-card text-emerald-950 border border-emerald-300 shadow-2xs">
            <Settings className="w-3.5 h-3.5 text-emerald-700" /> Cockpit Configuration
          </div>
          <h1 className="text-2xl sm:text-3xl font-black text-slate-950 tracking-tight">
            Settings & Data Backups
          </h1>
          <p className="text-xs sm:text-sm text-slate-700 font-medium leading-relaxed">
            Configure your AI provider credentials, daily study schedule parameters, and export your preparation logs and Error Book.
          </p>
        </div>
      </div>

      {savedSuccess && (
        <div className="p-4 rounded-2xl luxury-glass-emerald border border-emerald-400 text-emerald-950 text-xs font-black flex items-center gap-2 shadow-sm animate-in fade-in duration-200">
          <CheckCircle2 className="w-4 h-4 text-emerald-700" /> Preferences saved successfully!
        </div>
      )}

      {/* Section 1: Groq AI Provider Settings - Liquid Glass */}
      <div className="luxury-glass border border-white/90 rounded-3xl p-6 sm:p-7 shadow-md space-y-4">
        <div className="flex items-center justify-between border-b border-emerald-200/50 pb-3">
          <h3 className="text-sm font-black text-slate-950 flex items-center gap-2">
            <Bot className="w-4 h-4 text-emerald-700" /> Groq AI Engine Setup
          </h3>
          <span className="text-xs text-slate-600 font-mono font-bold">Ultra-Fast Inference</span>
        </div>

        <div className="space-y-3 text-xs">
          <div>
            <label className="font-extrabold text-slate-900 block mb-1">Groq API Key:</label>
            <div className="flex items-center gap-2">
              <input
                type="password"
                placeholder="gsk_..."
                value={groqKey}
                onChange={(e) => setGroqKey(e.target.value)}
                className="flex-1 bg-white/90 border border-slate-200 rounded-xl p-2.5 text-slate-950 font-mono font-bold focus:outline-none focus:border-emerald-500 shadow-2xs"
              />
            </div>
            <p className="text-[11px] text-slate-600 mt-1 font-medium">
              Your key is stored securely in your browser and used for server-side proxy calls. You can get a free key from{" "}
              <a
                href="https://console.groq.com/keys"
                target="_blank"
                rel="noreferrer"
                className="text-emerald-800 font-extrabold hover:underline"
              >
                console.groq.com/keys
              </a>
              .
            </p>
          </div>

          <div>
            <label className="font-extrabold text-slate-900 block mb-1">AI Model:</label>
            <select
              value={selectedModel}
              onChange={(e) => setSelectedModel(e.target.value)}
              className="w-full bg-white/90 border border-slate-200 rounded-xl p-2.5 text-slate-950 focus:outline-none focus:border-emerald-500 font-bold shadow-2xs"
            >
              <option value="openai/gpt-oss-120b">openai/gpt-oss-120b (Recommended for GATE CS reasoning)</option>
              <option value="openai/gpt-oss-20b">openai/gpt-oss-20b (Fast Inference)</option>
              <option value="qwen/qwen3.8-27b">qwen/qwen3.8-27b (High Performance)</option>
              <option value="llama-3.3-70b-versatile">llama-3.3-70b-versatile</option>
              <option value="llama-3.1-8b-instant">llama-3.1-8b-instant</option>
            </select>
          </div>
        </div>
      </div>

      {/* Section 2: Study Plan Rules & Profile - Liquid Glass */}
      <div className="luxury-glass border border-white/90 rounded-3xl p-6 sm:p-7 shadow-md space-y-4">
        <div className="flex items-center justify-between border-b border-emerald-200/50 pb-3">
          <h3 className="text-sm font-black text-slate-950 flex items-center gap-2">
            <Clock className="w-4 h-4 text-emerald-700" /> Study Profile & Schedule Parameters
          </h3>
          <span className="text-xs text-slate-600 font-mono font-bold">Section 2.1 Fixed Timeline</span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
          <div className="p-4 rounded-2xl luxury-glass-card border border-emerald-200/80 space-y-1 shadow-2xs">
            <span className="text-slate-600 block font-extrabold">Fixed Preparation Start:</span>
            <span className="text-sm font-mono font-black text-slate-950">{FIXED_PLAN_START_DATE}</span>
            <span className="text-[10px] text-slate-500 block font-bold">Day 1 of 90 Sequence</span>
          </div>

          <div className="p-4 rounded-2xl luxury-glass-card border border-emerald-200/80 space-y-1 shadow-2xs">
            <span className="text-slate-600 block font-extrabold">Fixed Preparation Finish:</span>
            <span className="text-sm font-mono font-black text-slate-950">{FIXED_PLAN_END_DATE}</span>
            <span className="text-[10px] text-slate-500 block font-bold">Day 90 Master Completion</span>
          </div>
        </div>

        <div className="text-xs">
          <label className="font-extrabold text-slate-900 block mb-1">Target Daily Study Hours:</label>
          <select
            value={dailyHours}
            onChange={(e) => setDailyHours(e.target.value)}
            className="w-full bg-white/90 border border-slate-200 rounded-xl p-2.5 text-slate-950 focus:outline-none focus:border-emerald-500 font-bold shadow-2xs"
          >
            <option value="4">4 Hours / Day (Compressed Profile)</option>
            <option value="6">6 Hours / Day (Recommended Master Schedule)</option>
            <option value="8">8+ Hours / Day (Intensive Problem Solving)</option>
          </select>
        </div>

        <button
          onClick={handleSaveSettings}
          className="px-6 py-2.5 rounded-xl metallic-emerald-btn text-white text-xs font-black shadow-md cursor-pointer transition-all hover:scale-102"
        >
          Save Preferences
        </button>
      </div>

      {/* Section 3: Data Export & Reset - Liquid Glass */}
      <div className="luxury-glass border border-white/90 rounded-3xl p-6 sm:p-7 shadow-md space-y-4">
        <div className="flex items-center justify-between border-b border-emerald-200/50 pb-3">
          <h3 className="text-sm font-black text-slate-950 flex items-center gap-2">
            <Download className="w-4 h-4 text-emerald-700" /> Data Backup & Export
          </h3>
          <span className="text-xs text-slate-600 font-mono font-bold">Offline-First Ownership</span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
          <button
            onClick={handleExportErrorBookCsv}
            className="p-4 rounded-2xl luxury-glass-card border border-white/90 hover:border-emerald-400 text-left flex items-start gap-3 transition-all group shadow-2xs cursor-pointer"
          >
            <FileText className="w-5 h-5 text-rose-600 shrink-0 mt-0.5" />
            <div>
              <span className="font-black text-slate-950 block group-hover:text-emerald-950 transition-colors">Download Error Book CSV</span>
              <span className="text-[11px] text-slate-600 font-medium">All recorded mistakes and correct concepts</span>
            </div>
          </button>

          <button
            onClick={handleExportPreparationReport}
            className="p-4 rounded-2xl luxury-glass-card border border-white/90 hover:border-emerald-400 text-left flex items-start gap-3 transition-all group shadow-2xs cursor-pointer"
          >
            <Download className="w-5 h-5 text-emerald-700 shrink-0 mt-0.5" />
            <div>
              <span className="font-black text-slate-950 block group-hover:text-emerald-950 transition-colors">Download Preparation Report</span>
              <span className="text-[11px] text-slate-600 font-medium">Comprehensive Markdown study summary</span>
            </div>
          </button>
        </div>

        <div className="pt-4 border-t border-emerald-200/40 flex justify-between items-center text-xs">
          <span className="text-slate-600 font-medium">Need to reset your progress state from scratch?</span>
          <button
            onClick={handleClearProgress}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl luxury-glass-card hover:bg-rose-100 text-rose-950 border border-rose-300 font-black transition-colors cursor-pointer shadow-2xs"
          >
            <Trash2 className="w-3.5 h-3.5 text-rose-600" /> Reset Local Data
          </button>
        </div>
      </div>
    </div>
  );
}
